# Generated by Django 4.1.3 on 2022-11-06 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='klient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=45)),
                ('nazwisko', models.CharField(max_length=45)),
                ('adres_zamieszkania', models.CharField(max_length=45)),
                ('data_urodzenia', models.DateTimeField()),
                ('mail', models.CharField(max_length=45)),
                ('numer_telefonu', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='magazyn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kraj', models.CharField(max_length=45)),
                ('miasto', models.CharField(max_length=45)),
                ('ulica', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='produkt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=45)),
                ('cena', models.DecimalField(decimal_places=10, max_digits=10)),
                ('producent', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='sklep_elektroniczny',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kraj', models.CharField(max_length=45)),
                ('miasto', models.CharField(max_length=45)),
                ('ulica', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='tranzakcja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_tranzakcji', models.DateTimeField()),
                ('koszt_tranzakcji', models.DecimalField(decimal_places=10, max_digits=10)),
                ('klient_id_klienta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ideas.klient')),
                ('sklep_elektroniczny_id_sklepu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ideas.sklep_elektroniczny')),
            ],
        ),
        migrations.CreateModel(
            name='dostepnosc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dostepnosc', models.CharField(choices=[('T', 'Yes'), ('N', 'Not')], default='N', max_length=1)),
                ('ilosc', models.IntegerField()),
                ('sklep_czy_magazyn', models.CharField(choices=[('S', 'Sklep'), ('M', 'Magazyn')], default='S', max_length=1)),
                ('magazyn_id_magazynu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ideas.magazyn')),
                ('produkt_id_produktu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ideas.produkt')),
                ('sklep_elektroniczny_id_sklepu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ideas.sklep_elektroniczny')),
            ],
        ),
    ]
