# Generated by Django 4.1.3 on 2022-11-07 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='produkt_has_tranzakcja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produkt_id_produktu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ideas.produkt')),
                ('tranzakcja_id_tranzakcji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ideas.tranzakcja')),
            ],
        ),
    ]
