# Generated by Django 4.1.3 on 2022-11-13 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0002_produkt_has_tranzakcja'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkt',
            name='rodzaj',
            field=models.CharField(default='null', max_length=45),
            preserve_default=False,
        ),
    ]
