# Generated by Django 4.1.3 on 2022-11-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0004_alter_dostepnosc_dostepnosc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produkt_has_tranzakcja',
            old_name='nazwa_produktu',
            new_name='id_produktu',
        ),
        migrations.RenameField(
            model_name='produkt_has_tranzakcja',
            old_name='kod_tranzakcji',
            new_name='id_tranzakcji',
        ),
        migrations.AddField(
            model_name='klient',
            name='id_klienta',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='magazyn',
            name='id_magazynu',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produkt',
            name='id_produktu',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sklep_elektroniczny',
            name='id_sklepu_elektronicznego',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tranzakcja',
            name='id_tranzakcji',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
