# Generated by Django 4.1.3 on 2022-11-21 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0005_rename_nazwa_produktu_produkt_has_tranzakcja_id_produktu_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tranzakcja',
            options={},
        ),
        migrations.RenameField(
            model_name='dostepnosc',
            old_name='magazyn_ulica',
            new_name='id_magazynu',
        ),
        migrations.RenameField(
            model_name='dostepnosc',
            old_name='nazwa_produktu',
            new_name='id_produktu',
        ),
        migrations.RenameField(
            model_name='dostepnosc',
            old_name='sklep_elektroniczny_ulica',
            new_name='id_sklepu_elektronicznego',
        ),
        migrations.RenameField(
            model_name='tranzakcja',
            old_name='nazwisko_klienta',
            new_name='id_klienta',
        ),
        migrations.RenameField(
            model_name='tranzakcja',
            old_name='ulica_sklepu',
            new_name='id_sklepu_elektronicznego',
        ),
        migrations.RemoveField(
            model_name='tranzakcja',
            name='kod_tranzakcji',
        ),
    ]
