# Generated by Django 4.1.3 on 2022-11-21 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0006_alter_tranzakcja_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dostepnosc',
            name='sklep_czy_magazyn',
            field=models.CharField(choices=[('SKLEP', 'Sklep'), ('MAGAZYN', 'Magazyn')], default='SKLEP', max_length=7),
        ),
    ]
