# Generated by Django 4.1.3 on 2022-11-21 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0007_alter_dostepnosc_sklep_czy_magazyn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dostepnosc',
            name='sklep_czy_magazyn',
        ),
    ]
