# Generated by Django 4.1.3 on 2022-11-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0008_remove_dostepnosc_sklep_czy_magazyn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dostepnosc',
            name='dostepnosc',
        ),
        migrations.AddField(
            model_name='dostepnosc',
            name='sklep_czy_magazyn',
            field=models.CharField(choices=[('SKLEP', 'Sklep'), ('MAGAZYN', 'Magazyn')], default='SKLEP', max_length=7),
        ),
    ]
